print("\n")
print("Nama Zefri Fahlevi Irdiansyah")
print("NIM 2206068")
print("Kelas IF-B")
print("Angkatan 22 \n")

print("Mohon Isi Data Diri Anda")
nama = input("Nama: ")
nim = input("Nim: ")
kelas = input("Kelas: ")
angkatan = input("Angkatan: ")
print("\n")

print("Terimakasih Telah Mengisi Data Diri ❤ \n")
print("Nama anda: {}".format(nama))
print("NIM anda: {}".format(nim))
print("Kelas anda: {}".format(kelas))
print("Angkatan anda: {}".format(angkatan))